/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd_Packge;

import BackEnd_Packge.Paciente;
import FrontEnd_Packge.TelaCadastroConsulta;
import java.util.ArrayList;


/**
 *
 * @author -
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        this.setVisible(true);
        initComponents();

    }
    ArrayList<Paciente> LDP = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PainelPaciente = new javax.swing.JPanel();
        LabelPaciente = new javax.swing.JLabel();
        BotaoCadastrarPaciente = new javax.swing.JButton();
        PainelMedico1 = new javax.swing.JPanel();
        LabelMedico = new javax.swing.JLabel();
        BotaoCadastrarMedico = new javax.swing.JButton();
        PainelEnfermeiro = new javax.swing.JPanel();
        LabelEnfermeiro = new javax.swing.JLabel();
        BotaoCadastroEnfermeiro = new javax.swing.JButton();
        PainelConsulta = new javax.swing.JPanel();
        LabelConsulta = new javax.swing.JLabel();
        BotaoCadastrarConsulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotaoConsultarEditarDeletar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de Clínica Hospitalar");

        PainelPaciente.setBackground(new java.awt.Color(153, 153, 153));

        LabelPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPaciente.setText("Paciente");

        BotaoCadastrarPaciente.setText("Cadastrar");
        BotaoCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPacienteLayout = new javax.swing.GroupLayout(PainelPaciente);
        PainelPaciente.setLayout(PainelPacienteLayout);
        PainelPacienteLayout.setHorizontalGroup(
            PainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastrarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelPacienteLayout.setVerticalGroup(
            PainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastrarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelMedico1.setBackground(new java.awt.Color(153, 153, 153));

        LabelMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMedico.setText("Médico");

        BotaoCadastrarMedico.setText("Cadastrar");
        BotaoCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMedico1Layout = new javax.swing.GroupLayout(PainelMedico1);
        PainelMedico1.setLayout(PainelMedico1Layout);
        PainelMedico1Layout.setHorizontalGroup(
            PainelMedico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMedico1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelMedico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastrarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelMedico1Layout.setVerticalGroup(
            PainelMedico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMedico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastrarMedico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelEnfermeiro.setBackground(new java.awt.Color(153, 153, 153));

        LabelEnfermeiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelEnfermeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEnfermeiro.setText("Enfermeiro");

        BotaoCadastroEnfermeiro.setText("Cadastrar");
        BotaoCadastroEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroEnfermeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelEnfermeiroLayout = new javax.swing.GroupLayout(PainelEnfermeiro);
        PainelEnfermeiro.setLayout(PainelEnfermeiroLayout);
        PainelEnfermeiroLayout.setHorizontalGroup(
            PainelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnfermeiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastroEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelEnfermeiroLayout.setVerticalGroup(
            PainelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnfermeiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastroEnfermeiro)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PainelConsulta.setBackground(new java.awt.Color(153, 153, 153));

        LabelConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsulta.setText("Consulta");

        BotaoCadastrarConsulta.setText("Cadastrar");
        BotaoCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConsultaLayout = new javax.swing.GroupLayout(PainelConsulta);
        PainelConsulta.setLayout(PainelConsultaLayout);
        PainelConsultaLayout.setHorizontalGroup(
            PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastrarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelConsultaLayout.setVerticalGroup(
            PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastrarConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Consulta/Edição de Dados");

        BotaoConsultarEditarDeletar.setText("Consultar/Editar");
        BotaoConsultarEditarDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarEditarDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(BotaoConsultarEditarDeletar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoConsultarEditarDeletar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PainelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PainelMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PainelEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PainelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PainelEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelMedico1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarPacienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroPaciente TCC = new TelaCadastroPaciente();
        //this.setVisible(false);
    }//GEN-LAST:event_BotaoCadastrarPacienteActionPerformed

    private void BotaoCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarMedicoActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedicoEnfermeiro TCM = new TelaCadastroMedicoEnfermeiro();
    }//GEN-LAST:event_BotaoCadastrarMedicoActionPerformed

    private void BotaoConsultarEditarDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarEditarDeletarActionPerformed
        // TODO add your handling code here:
        TelaGeralConsulta TGC = new TelaGeralConsulta();
    }//GEN-LAST:event_BotaoConsultarEditarDeletarActionPerformed

    private void BotaoCadastroEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroEnfermeiroActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedicoEnfermeiro TCM = new TelaCadastroMedicoEnfermeiro();
    }//GEN-LAST:event_BotaoCadastroEnfermeiroActionPerformed

    private void BotaoCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarConsultaActionPerformed
        // TODO add your handling code here:
        TelaCadastroConsulta TC = new TelaCadastroConsulta();
    }//GEN-LAST:event_BotaoCadastrarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarConsulta;
    private javax.swing.JButton BotaoCadastrarMedico;
    private javax.swing.JButton BotaoCadastrarPaciente;
    private javax.swing.JButton BotaoCadastroEnfermeiro;
    private javax.swing.JButton BotaoConsultarEditarDeletar;
    private javax.swing.JLabel LabelConsulta;
    private javax.swing.JLabel LabelEnfermeiro;
    private javax.swing.JLabel LabelMedico;
    private javax.swing.JLabel LabelPaciente;
    private javax.swing.JPanel PainelConsulta;
    private javax.swing.JPanel PainelEnfermeiro;
    private javax.swing.JPanel PainelMedico1;
    private javax.swing.JPanel PainelPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
