/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd_Packge;

import FrontEnd_Packge.Main;
import BackEnd_Packge.ContatoTelEmail;
import BackEnd_Packge.Endereco;
import BackEnd_Packge.Genero;
import BackEnd_Packge.Paciente;
import BackEnd_Packge.ArrayListClass.PacienteArrayList;
import BackEnd_Packge.Responsavel;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.DataFormatException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author -
 */

public class TelaCadastroPaciente extends javax.swing.JFrame {

    //private  ArrayList<Paciente> listaDePacientes;

    /**
     * Creates new form TelaCadastroPaciente
     */
    public TelaCadastroPaciente() {
        //listaDePacientes = ListaDePacientes;
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FieldNomeCompleto = new javax.swing.JTextField();
        FormattedDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FieldBairro = new javax.swing.JTextField();
        FieldNumero = new javax.swing.JTextField();
        FieldCep = new javax.swing.JTextField();
        FieldRua = new javax.swing.JTextField();
        FieldCidade = new javax.swing.JTextField();
        FieldEstado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FieldTelefone = new javax.swing.JTextField();
        FieldEmail = new javax.swing.JTextField();
        FieldCelular = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        BotaoSalvar = new javax.swing.JButton();
        BotaoFechar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FieldNomeResponsavel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        FieldEmailResponável = new javax.swing.JTextField();
        FieldTelefoneResponsavel = new javax.swing.JTextField();
        FieldCelularResponsável = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextObservacaoGeral = new javax.swing.JTextArea();
        FieldIdade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Paciente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome Completo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Endereço");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Contato/Email");

        FormattedDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FormattedDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FormattedDataNascimento.setToolTipText("dd/mm/yyyy");
        FormattedDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedDataNascimentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Rua");

        jLabel7.setText("Número");

        jLabel8.setText("Bairro");

        jLabel9.setText("Cidade");

        jLabel10.setText("Estado");

        jLabel11.setText("Cep");

        FieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBairroActionPerformed(evt);
            }
        });

        FieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldRuaActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefone");

        jLabel13.setText("Celular");

        jLabel14.setText("Email");

        FieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTelefoneActionPerformed(evt);
            }
        });

        FieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldEmailActionPerformed(evt);
            }
        });

        FieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCelularActionPerformed(evt);
            }
        });

        jLabel15.setText("Genero");

        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"MASCULINO", "FEMININO"}));
        ComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGeneroActionPerformed(evt);
            }
        });

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        BotaoFechar.setText("Fechar");
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Contato Responsável");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Nome Responsável");

        FieldNomeResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNomeResponsavelActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Contato/Email Responsável");

        jLabel19.setText("Telefone");

        jLabel20.setText("Email");

        FieldEmailResponável.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldEmailResponávelActionPerformed(evt);
            }
        });

        FieldTelefoneResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTelefoneResponsavelActionPerformed(evt);
            }
        });

        FieldCelularResponsável.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCelularResponsávelActionPerformed(evt);
            }
        });

        jLabel21.setText("Celular");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Observação Geral");

        TextObservacaoGeral.setColumns(20);
        TextObservacaoGeral.setRows(5);
        jScrollPane1.setViewportView(TextObservacaoGeral);

        jLabel23.setText("Idade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FieldTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FieldCelularResponsável, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FieldEmailResponável, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(FieldNomeResponsavel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(294, 294, 294)
                                                                .addComponent(jLabel1))
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(FormattedDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel23)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(FieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(FieldNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(FieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel7)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(FieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel8)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(FieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel17)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(FieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(FieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel15)
                                                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(FieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(FieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(FieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(1, 1, 1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(BotaoSalvar)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotaoFechar)))
                                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FormattedDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldIdade)
                                        .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(FieldBairro)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(FieldNumero)
                                        .addComponent(FieldRua))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldCidade)
                                        .addComponent(FieldEstado)
                                        .addComponent(jLabel11)
                                        .addComponent(FieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(FieldTelefone)
                                        .addComponent(FieldCelular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(FieldEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel21)
                                        .addComponent(FieldTelefoneResponsavel)
                                        .addComponent(FieldCelularResponsável))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(FieldEmailResponável))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotaoSalvar)
                                        .addComponent(BotaoFechar))
                                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormattedDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormattedDataNascimentoActionPerformed

    private void FieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldRuaActionPerformed

    private void FieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBairroActionPerformed

    private void FieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTelefoneActionPerformed

    private void FieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldEmailActionPerformed

    private void FieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCelularActionPerformed

    private void FieldEmailResponávelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldEmailResponávelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldEmailResponávelActionPerformed

    private void FieldTelefoneResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTelefoneResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTelefoneResponsavelActionPerformed

    private void FieldCelularResponsávelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCelularResponsávelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCelularResponsávelActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
        //Botao de Salvamento do objeto paciente
        try {
            if (getNomeCompleto().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de nome");
            } else if (getRua().isEmpty() || String.valueOf(getNumero()).isEmpty() || String.valueOf(getCep()).isEmpty() || getBairro().isEmpty() || getCidade().isEmpty() || getEstado().isEmpty()) {
                //Verificar se o campo de endereço estão preenchidos
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de endereço");
            } else if (getTelefonePaciente().isEmpty() || getCelularPaciente().isEmpty() || getEmailPaciente().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de contato pessoal");
            } else if (getDataNascimento() == null) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de data corretamente");
            } else {
                Endereco e = new Endereco(
                        getRua(),
                        getNumero(),
                        getBairro(),
                        getCidade(),
                        getEstado(),
                        getCep());

                ContatoTelEmail c = new ContatoTelEmail(
                        getTelefonePaciente(),
                        getCelularPaciente(),
                        getEmailPaciente());

                Responsavel r = new Responsavel(
                        getTelefoneResponsavel(),
                        getCelularResponsavel(),
                        getEmailResponsavel(),
                        getNomeResponsavel());

                Paciente p = new Paciente(
                        getNomeCompleto(),
                        getDataNascimento(),//Consertar
                        e,
                        c,
                        getGenero(),
                        getIdade(),
                        new Date(),
                        getObservacaoGeral(),
                        r);

                PacienteArrayList.ListaDePacientes.add(p);
                JOptionPane.showMessageDialog(null, "Paciente registrado com sucesso!");
                limparTela();
            }
        } catch (Exception e) {//Adicionar mais erros
            System.out.println(e);
        }


    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void FieldNomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNomeResponsavelActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void ComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Funções auxiliares
    public String getNomeCompleto() {
        return this.FieldNomeCompleto.getText();
    }

    public LocalDate getDataNascimento() {
        try {
            LocalDate dataN = LocalDate.parse(
                    this.FormattedDataNascimento.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy")

            );
            // Date data = Date.from(dataN.atStartOfDay(ZoneId.systemDefault()).toInstant());
            return dataN;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "A data deve ser inserida no formato dd/mm/yyyy");
            System.out.println(e);
        }
        return null;

    }

    public String getRua() {
        return this.FieldRua.getText();
    }

    public int getNumero() {
        return Integer.parseInt(this.FieldNumero.getText());
    }

    public String getBairro() {
        return this.FieldBairro.getText();
    }

    public String getCidade() {
        return this.FieldCidade.getText();
    }

    public String getEstado() {
        return this.FieldEstado.getText();
    }

    public int getIdade() {
        return Integer.parseInt(this.FieldIdade.getText());
    }


    public int getCep() {
        return Integer.parseInt(this.FieldCep.getText());
    }

    public String getTelefonePaciente() {
        return this.FieldTelefone.getText();
    }

    public String getCelularPaciente() {
        return this.FieldCelular.getText();
    }

    public String getEmailPaciente() {
        return this.FieldEmail.getText();
    }

    public String getNomeResponsavel() {
        return this.FieldNomeResponsavel.getText();
    }

    public String getTelefoneResponsavel() {
        return this.FieldTelefoneResponsavel.getText();
    }

    public String getCelularResponsavel() {
        return this.FieldCelularResponsável.getText();
    }

    public String getEmailResponsavel() {
        return this.FieldEmailResponável.getText();
    }

    public String getObservacaoGeral() {
        return this.TextObservacaoGeral.getText();
    }

    public Genero getGenero() {
        return Genero.valueOf(this.ComboBoxGenero.getSelectedItem().toString());


    /*if (this.ComboBoxGenero.getSelectedItem() == "Feminimo") {
        return Genero.FEMININO;
    } else {
        return Genero.MASCULINO;
    }*/
    }

    public void limparTela() {
        this.FieldNomeCompleto.setText("");
        this.FormattedDataNascimento.setText("");
        this.FieldRua.setText("");
        this.FieldNumero.setText("");
        this.FieldBairro.setText("");
        this.FieldCidade.setText("");
        this.FieldEstado.setText("");
        this.FieldCep.setText("");
        this.FieldTelefone.setText("");
        this.FieldCelular.setText("");
        this.FieldEmail.setText("");
        this.FieldNomeResponsavel.setText("");
        this.FieldTelefoneResponsavel.setText("");
        this.FieldCelularResponsável.setText("");
        this.FieldEmailResponável.setText("");
        this.TextObservacaoGeral.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JTextField FieldBairro;
    private javax.swing.JTextField FieldCelular;
    private javax.swing.JTextField FieldCelularResponsável;
    private javax.swing.JTextField FieldCep;
    private javax.swing.JTextField FieldCidade;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldEmailResponável;
    private javax.swing.JTextField FieldEstado;
    private javax.swing.JTextField FieldIdade;
    private javax.swing.JTextField FieldNomeCompleto;
    private javax.swing.JTextField FieldNomeResponsavel;
    private javax.swing.JTextField FieldNumero;
    private javax.swing.JTextField FieldRua;
    private javax.swing.JTextField FieldTelefone;
    private javax.swing.JTextField FieldTelefoneResponsavel;
    private javax.swing.JFormattedTextField FormattedDataNascimento;
    private javax.swing.JTextArea TextObservacaoGeral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
