/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd_Packge;

import BackEnd_Packge.*;
import BackEnd_Packge.ArrayListClass.EnfermeiroArrayList;
import BackEnd_Packge.ArrayListClass.MedicoArrayList;

import java.awt.event.ActionEvent;

import javax.swing.JFrame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author -
 */
public class TelaCadastroMedicoEnfermeiro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroMedico
     */
    public TelaCadastroMedicoEnfermeiro() {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        FieldNomeCompleto = new javax.swing.JTextField();
        TextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        FieldRua = new javax.swing.JTextField();
        FieldCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FieldNumero = new javax.swing.JTextField();
        FieldEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FieldBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FieldCep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FieldTelefone = new javax.swing.JTextField();
        FieldEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        FieldCelular = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FieldCmr = new javax.swing.JTextField();
        FieldEspecialidades = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CheckBoxRaioX = new javax.swing.JCheckBox();
        BotaoCadastrar = new javax.swing.JButton();
        BotaoFechar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        FieldCH1 = new javax.swing.JTextField();
        FieldSetor = new javax.swing.JTextField();
        CheckBoxCirurgiao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome Completo");

        TextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        TextFieldDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldDataNascimento.setToolTipText("");
        TextFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDataNascimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Endereço");

        FieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldRuaActionPerformed(evt);
            }
        });

        jLabel6.setText("Rua");

        jLabel9.setText("Cidade");

        jLabel7.setText("Número");

        jLabel10.setText("Estado");

        FieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBairroActionPerformed(evt);
            }
        });

        jLabel8.setText("Bairro");

        jLabel11.setText("Cep");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Contato/Email");

        jLabel12.setText("Telefone");

        jLabel14.setText("Email");

        FieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTelefoneActionPerformed(evt);
            }
        });

        FieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldEmailActionPerformed(evt);
            }
        });

        jLabel13.setText("Celular");

        FieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCelularActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Genero");

        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));
        ComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGeneroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Especificações do Enfermeiro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("NumeroCMR");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Cirurgião");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Especialidades");

        FieldCmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCmrActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setText("Médico/Enfermeiro");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel20.setText("Especificações do Médico");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Treinamento Raio X");

        CheckBoxRaioX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxRaioXActionPerformed(evt);
            }
        });

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        BotaoFechar.setText("Fechar");
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico", "Enfermeiro" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Tipo Cadastro");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Setor");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Carga Horária");

        FieldCH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCH1ActionPerformed(evt);
            }
        });

        FieldSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldSetorActionPerformed(evt);
            }
        });

        CheckBoxCirurgiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxCirurgiaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldEstado))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldCmr, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(166, 166, 166)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CheckBoxRaioX))
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FieldEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CheckBoxCirurgiao)))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(FieldRua)
                            .addComponent(FieldBairro)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(FieldNumero)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel19)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldCidade)
                    .addComponent(jLabel11)
                    .addComponent(FieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(FieldTelefone)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(FieldEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(FieldCmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(FieldCH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(FieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CheckBoxRaioX)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoCadastrar)
                            .addComponent(BotaoFechar)))
                    .addComponent(CheckBoxCirurgiao))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDataNascimentoActionPerformed

    private void FieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldRuaActionPerformed

    private void FieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBairroActionPerformed

    private void FieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTelefoneActionPerformed

    private void FieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldEmailActionPerformed

    private void FieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCelularActionPerformed

    private void ChechBoxCirurgiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChechBoxCirurgiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChechBoxCirurgiaoActionPerformed

    private void FieldCmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCmrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCmrActionPerformed

    private void CheckBoxRaioXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxRaioXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxRaioXActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        // TODO add your handling code here:\
        if (this.ComboBoxTipo.getSelectedItem() == "Médico") {
            //Médico
            if (getNomeCompleto().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de nome");
            } else if (getRua().isEmpty() || String.valueOf(getNumero()).isEmpty() || String.valueOf(getCep()).isEmpty() || getBairro().isEmpty() || getCidade().isEmpty() || getEstado().isEmpty()) {
                //Verificar se o campo de endereço estão preenchidos
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de endereço");
            } else if (getTelefone().isEmpty() || getCelular().isEmpty() || getEmail().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de contato pessoal");
            } else if (getDataNascimento() == null) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de data corretamente");
            } else {
                Endereco e = new Endereco(
                        getRua(),
                        getNumero(),
                        getBairro(),
                        getCidade(),
                        getEstado(),
                        getCep());
                ContatoTelEmail c = new ContatoTelEmail(
                        getTelefone(),
                        getCelular(),
                        getEmail());
                Medico m = new Medico(
                        getNomeCompleto(),
                        getDataNascimento(),
                        e,
                        c,
                        getGenero(),
                        getCMR(),
                        getEspecialidades(),
                        getCirurgiao(),
                        getCH(),
                        getSetor());
                MedicoArrayList.ListaDeMedicos.add(m);
                JOptionPane.showMessageDialog(null, "Médico cadastrado com sucesso!");
                limparTela();
            }
        } else {
            if (getNomeCompleto().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de nome");
            } else if (getRua().isEmpty() || String.valueOf(getNumero()).isEmpty() || String.valueOf(getCep()).isEmpty() || getBairro().isEmpty() || getCidade().isEmpty() || getEstado().isEmpty()) {
                //Verificar se o campo de endereço estão preenchidos
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de endereço");
            } else if (getTelefone().isEmpty() || getCelular().isEmpty() || getEmail().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de contato pessoal");
            } else if (getDataNascimento() == null) {
                JOptionPane.showMessageDialog(null, "Preencha o campo de data corretamente");
            } else {
                //Enfermeiro
                Endereco e = new Endereco(
                        getRua(),
                        getNumero(),
                        getBairro(),
                        getCidade(),
                        getEstado(),
                        getCep());
                ContatoTelEmail c = new ContatoTelEmail(
                        getTelefone(),
                        getCelular(),
                        getEmail());

                Enfermeiro enf = new Enfermeiro(
                        getNomeCompleto(),
                        getDataNascimento(),
                        e,
                        c,
                        getGenero(),
                        getSetor(),
                        getCH(),
                        getTreinadoRx());
                EnfermeiroArrayList.ListaDeEnfermeiro.add(enf);
                JOptionPane.showMessageDialog(null, "Enfermeiro cadastrado com sucesso!");
                limparTela();
            }
        }
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void FieldCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCHActionPerformed

    private void FieldCH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCH1ActionPerformed

    private void FieldSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldSetorActionPerformed

    private void CheckBoxCirurgiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxCirurgiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxCirurgiaoActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
        if (this.ComboBoxTipo.getSelectedItem() == "Médico") {
            this.CheckBoxRaioX.setEnabled(false);
            this.CheckBoxCirurgiao.setEnabled(true);
            this.FieldEspecialidades.setEnabled(true);
        } else if (this.ComboBoxTipo.getSelectedItem() == "Enfermeiro") {
            this.CheckBoxRaioX.setEnabled(true);
            this.CheckBoxCirurgiao.setEnabled(false);
            this.FieldEspecialidades.setEnabled(false);
        }
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void ComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedicoEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedicoEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedicoEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedicoEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMedicoEnfermeiro().setVisible(true);
            }
        });
    }

    //Metodos auxiliares
    private String getNomeCompleto() {
        return this.FieldNomeCompleto.getText();
    }

    private String getRua() {
        return this.FieldRua.getText();
    }

    private int getNumero() {
        return Integer.parseInt(this.FieldNumero.getText());
    }

    private String getBairro() {
        return this.FieldBairro.getText();
    }

    private String getCidade() {
        return this.FieldCidade.getText();
    }

    private String getEstado() {
        return this.FieldEstado.getText();
    }

    private int getCep() {
        return Integer.parseInt(this.FieldCep.getText());
    }

    private String getTelefone() {
        return this.FieldTelefone.getText();
    }

    private String getCelular() {
        return this.FieldCelular.getText();
    }

    private String getEmail() {
        return this.FieldEmail.getText();
    }

    private Genero getGenero() {
        return Genero.valueOf(this.ComboBoxGenero.getSelectedItem().toString());
    }

    private int getCMR() {
        return Integer.parseInt(this.FieldCmr.getText());
    }

    private boolean getCirurgiao() {
        return this.CheckBoxCirurgiao.isSelected();
    }

    private int getCH() {
        return Integer.parseInt(this.FieldCH1.getText());
    }

    private String getSetor() {
        return this.FieldSetor.getText();
    }

    private String[] getEspecialidades() {

        return this.FieldEspecialidades.getText().split(";");
    }

    private LocalDate getDataNascimento() {//Consertar depois
        try {
            LocalDate dataN = LocalDate.parse(
                    this.TextFieldDataNascimento.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy")
            );

            return dataN;

        } catch (Exception e) {
            System.err.println(e);
        }
        return null;
    }

    private boolean getTreinadoRx() {
        return this.CheckBoxRaioX.isSelected();
    }
    private void limparTela() {
    this.FieldNomeCompleto.setText("");
    this.TextFieldDataNascimento.setText("");
    this.FieldRua.setText("");
    this.FieldNumero.setText("");
    this.FieldBairro.setText("");
    this.FieldCidade.setText("");
    this.FieldEstado.setText("");
    this.FieldCep.setText("");
    this.FieldTelefone.setText("");
    this.FieldCelular.setText("");
    this.FieldEmail.setText("");
    this.FieldEspecialidades.setText("");


}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JCheckBox CheckBoxCirurgiao;
    private javax.swing.JCheckBox CheckBoxRaioX;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JTextField FieldBairro;
    private javax.swing.JTextField FieldCH1;
    private javax.swing.JTextField FieldCelular;
    private javax.swing.JTextField FieldCep;
    private javax.swing.JTextField FieldCidade;
    private javax.swing.JTextField FieldCmr;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldEspecialidades;
    private javax.swing.JTextField FieldEstado;
    private javax.swing.JTextField FieldNomeCompleto;
    private javax.swing.JTextField FieldNumero;
    private javax.swing.JTextField FieldRua;
    private javax.swing.JTextField FieldSetor;
    private javax.swing.JTextField FieldTelefone;
    private javax.swing.JFormattedTextField TextFieldDataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
